echo(`
// <auto-generated />
#pragma warning disable

namespace T4.SourceGenerator.Example;

public static class Squares
{
`);
	for (var i = 0; i < 256; i++)
	{
echo(`
   public const int Squared${i} = ${ i * i };
`);
}
echo(`
}
`);